name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get deps
        run: flutter pub get
      - name: Generate icons
        run: dart run flutter_launcher_icons
      - name: Patch record_android plugin directly
        run: |
          FILE=$(find ~/.pub-cache -path "*record_android-*/android/build.gradle" | head -n 1)
          echo "Patching $FILE"
          sed -i 's/namespace.*//' "$FILE" || true
          sed -i 's/compileSdkVersion.*/compileSdkVersion 34/' "$FILE" || true
          sed -i 's/compileSdk.*/compileSdk 34/' "$FILE" || true
          sed -i 's/minSdkVersion.*/minSdkVersion 21/' "$FILE" || true
          sed -i 's/targetSdkVersion.*/targetSdkVersion 34/' "$FILE" || true
      - name: Run flutter build apk --release
        run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: SecureCrypt-APK
          path: build/app/outputs/flutter-apk/app-release.apk
